name: uplift-backend
services:
  - name: api
    type: web
    build:
      dockerfile: Dockerfile
    ports:
      - port: 10000
        protocol: http
    env:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    regions:
      - was
    instance_type: nano
